# Generated by Django 4.2.4 on 2023-08-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_units", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
