# Generated by Django 4.2.4 on 2023-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_units", "0005_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
