# Generated by Django 3.2 on 2023-12-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_units', '0008_auto_20230810_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
